# Machine Learning and Statistics Tasks 2020

## Task 1: sqrt2

This task was accomplished by writing the sqrt2(**its, prec**) Python function, shown below.

This function uses continued fractions to calculate a rational number that is an approximate value of the square root of 2 [1](#ref1). It uses a recursive algorithm to calculate and refine the numerator *p* and denominator *q* of the approximate value step by step for a number of iterations **its** (200 in this case for a very accurate approximation). The algorithm is as follows:

p<sub>n+1</sub> = p<sub>n</sub> + 2q<sub>n</sub><br>
q<sub>n+1</sub> = p<sub>n</sub> + q<sub>n</sub>

where *p<sub>n+1</sub>* is the next step of the numerator, *p<sub>n</sub>* is the previous step of the numerator, and *q<sub>n+1</sub>* and *q<sub>n</sub>* are the next and previous steps of the numerator and denominator respectively.

The function then takes the final calculated values for *p* and *q* and uses a long division algorithm to calculate digits of the square root of 2 decimal by decimal. This algorithm is a computational implementation of pen-and-paper long division. The algorithm has 5 steps:

1. Calculate the result of division of *p* and *q*.
2. Append the result from Step 1 to the string that is to be returned by the function.
3. Calculate the remainder after division of *p* and *q*.
4. Make *p* equal the result from Step 3 multipled by 10.
5. Repeat for **prec** number of digits (100 in this case).

The algorithm is defined as follows:

In [15]:
# sqrt2 function definition, calculates the square
# root of 2 through long division and returns 
# a string with the digits of the square root of 2
# sqrt2 takes in its, which is number of iterations of
# the continued fractions recursive algorithm
# and prec which indicates to how many decimal
# places the string with the digits of the square
# root of 2 to be returned has
def sqrt2(its, prec):

    # pold is the numerator at previous step, pnew is numerator at next step
    pold = 1
    pnew = 0

    # qold is the denominator at previous step, qnew is denominator at next step
    qold = 1
    qnew = 0

    # This calculates an approximation of sqrt(2) as a rational number
    # with pnew and pold as numerators (in the next and previous step
    # respectively) and qnew and qold as denominators (in the next and 
    # previous steps respectively) for its iterations 
    for i in range(0, its):

        # This is the recursion algorithm, derived from
        # the formula for continued fractions
        pnew = pold + 2*qold
        qnew = pold + qold

        # Make the new numerator and denominator
        # equal the old numerator and denominator
        # for the next step in the loop
        pold = pnew
        qold = qnew

    # This appends the first digit of sqrt(2)
    # to output_string (the string to be
    # returned)
    output_string = str(pnew // qnew) + "."

    # This is the first step in the long division algorithm
    # pnew is set to the remainder of pnew and qnew after
    # division and multipled by ten for the first decimal
    # place
    pnew = (pnew % qnew) * 10

    # This performs the long division algorithm for each decimal place
    # (defined by prec) and appends the digits of sqrt(2) 
    # digit by digit to the output_string, which is returned 
    # at the end of the function
    for i in range(1, prec+1):
        output_string += str(pnew//qnew)
        pnew = (pnew % qnew) * 10

    # This returns the string, which has prec decimal places
    # of sqrt(2)
    return output_string

The square root of 2 to 100 decimal places is:

In [16]:
result = sqrt2(200, 100)

In [17]:
result

'1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727'

This is compared with this result taken from a square root of 2 calculator online [2](#ref2):

In [18]:
test = "1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727"

In [19]:
result == test

True

This result has been verified to be correct.

## Task 2: Chi-squared test
This task was accomplished using the dataset taken from Wikipedia article on the Chi-squared test [3](#ref3) https://en.wikipedia.org/wiki/Chi-squared_test

The task is to perform the Chi-squared test on a dataset of workers. This dataset has the number of workers in particular neighborhoods (marked A, B, C and D). The workers are delineated by what type of worker they are, i.e., whether they are white collar, blue collar or no collar workers.

The null hypothesis is that type of worker does not effect their choice of neighborhood. In other words, the number of X collar worker (where X is White, Blue or No) in a particular neighborhood is the same as the average of all the workers in that neighborhood.

First, the workers dataset is defined as a dataframe using the Pandas package:

In [9]:
# import pandas module
import pandas as pd
# define workers dataframe
workers = pd.DataFrame(
    # number of workers
    # different columns indicate different neighborhoods
    # different rows indicate different collars or types
    [
        [90,60,104,95],
        [30,50,51,20],
        [30,40, 45, 35],
    ],
    # define row labels
    index=["White collar","Blue collar", "No collar"],
    # define column labels
    columns=["A", "B", "C", "D"])
workers           

A   B    C   D
White collar  90  60  104  95
Blue collar   30  50   51  20
No collar     30  40   45  35

The **chi2_contingency** function taken from the **scipy.stats** package is used to calculate the Chi-squared statistic, p-value, degrees of freedom and expected values using this dataframe: [4](#ref4)

In [80]:
from scipy.stats import chi2_contingency
# Chi-squared statistic
print(chi2_contingency(workers)[0])
# p-value
print(chi2_contingency(workers)[1])
# degrees of freedom
print(chi2_contingency(workers)[2])
# numpy array of expected values
print(chi2_contingency(workers)[3])

24.5712028585826
0.0004098425861096696
6
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


24.57 (or 24.6 when rounded down) is the test statistic calculated in the Wikipedia article, so the result is verified. This value is the sum of the observed values minus the expected values, divided by the expected values.

The p-value associated with this statistic is approximately 0.00041. This means that we can safely reject the null hypothesis that the type or collar of the worker has no effect on choice of neighborhood as 0.00041 is much less than the critical value of 0.05 or 5% [5](#ref5).

The degrees of freedom in this instance is the number of rows minus 1 multiplied by the number of columns minus 1, which is the same as the number of neighborhoods -1 multipled by the number of types of workers -1. This equals 6.

The expected values are the average, mean or expected values of the number of workers calculated by multiplying the total number of workers in each neighborhood by the total number of workers by collar divided by the total number of workers (650). For instance, for the expected number of white collar workers in A:

In [81]:
(90+30+30)*((90 +60 +104+95)/650)

80.53846153846155

which is the value output by **chi2_contingency**:

In [83]:
print(chi2_contingency(workers)[3][0][0])

80.53846153846153


## References ##

[1] Numbers, constants and computation, Xavier Gourdon and Pascal Sebah, accessed 6 October 2020, <http://numbers.computation.free.fr/Constants/Sqrt2/sqrt2.html> <a name="ref1"></a><br>
[2] CATONMAT, Peteris Krumins, accessed 6 October 2020, <https://catonmat.net/tools/generate-sqrt2-digits> <a name="ref2"></a> <br>
[3] En.wikipedia.org. 2020. Chi-Squared Test. [online] Available at: <https://en.wikipedia.org/wiki/Chi-squared_test> [Accessed 7 November 2020]. <a name="ref3"></a><br> 
[4] Medium. 2020. Gentle Introduction To Chi-Square Test For Independence. [online] Available at: <https://towardsdatascience.com/gentle-introduction-to-chi-square-test-for-independence-7182a7414a95> [Accessed 7 November 2020]. <a name="ref4"></a><br> 
[5] Statistics How To. 2020. Chi-Square Statistic: How To Calculate It / Distribution - Statistics How To. [online] Available at: <https://www.statisticshowto.com/probability-and-statistics/chi-square/> [Accessed 7 November 2020]. <a name="ref5"></a><br>